name: Publish dbt Docs

on:
  push:
    branches:
      - dev  # Ajustado para sua branch 'dev'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # ESTA LINHA É O SEGREDO: Define a pasta padrão para todos os comandos run
    defaults:
      run:
        working-directory: ./exemplo_dbt

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dbt
        run: pip install dbt-core dbt-bigquery 

      - name: Instalar dependências
        run: dbt deps

      - name: Gerar Documentação
        env:
          DBT_PROFILES_DIR: ./ 
          # ... adicione aqui suas variáveis de ambiente/secrets ...
        run: dbt docs generate

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # O publish_dir precisa apontar para a pasta target DENTRO de exemplo_dbt
          publish_dir: ./exemplo_dbt/target