name: dbt_deploy_prod

on:
  push:
    branches:
      - main 

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./exemplo_dbt

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Install dependencies
        run: dbt deps

      - name: Authenticate GCP
        run: echo '${{ secrets.GCP_SA_KEY }}' > ./service-account-key.json

      - name: dbt Build (Production)
        env:
          DBT_PROFILES_DIR: ./ 
        run: dbt build --target prod