name: dbt_ci_pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  dbt_run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-bigquery
          dbt deps

      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ./service-account-key.json

      - name: Run dbt Build (Slim CI)
        env:
         
          DBT_PROFILES_DIR: ./ 
        run: dbt build --target dev 